/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import SphereMaterial from '../materials/SphereMaterial'

export function Sphere(
{
    ...props
}) 
{
  const { nodes } = useGLTF('./models/quadSphere.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}>
        <SphereMaterial
          transparent={ true }
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/quadSphere.glb')